### ISSUE TITLE
Serious security vulnerability: LFI (Local File Inclusion)

### ISSUE THREAD

**Issue by xmcp** [ht35268/bzShare#2]
`FilesDownloadHandler` (as well as other handlers) will not check the validity of the filename (or pathname).  So a hacker can pass a malicious paremeter like:

- `../../../../../../../../windows/win.ini`
- `../../../../../../../../etc/passwd`

## Solution
Store the files in the database or a virtualized filesystem, instead of real FS (recommended), or

Try to escape the pathname (not recommended)

## See more:
https://www.owasp.org/index.php/Input_Validation_Cheat_Sheet#File_Upload_Validation

**Comment by ht35268** [comment]
Yes, because I hadn't gain access to psycopg2 and did not learn SQL by the time, I didn't have chances to use a SQL DB.

You see I write `TODO` everywhere where invoked os.* operations because I did not like to use native filesystem. I am now creating a SQL-FS and am ready to push it whenever I like to.

I will reference this issue when the time is adequate.

**Comment by ht35268** [comment]
**Of course this base64+hexascii approach is dangerous and malice-vulnerable.**

**Comment by xmcp** [comment]
btw, `urllib.parse.quote` (same as `|u` in mako) is much more efficient than your binascii+base64 approach.

```python
>>> from urllib.parse import quote
>>> data='Hello World! This is a simple test.'*1000
>>> len(data)
35000
>>> len(quote(data))
49000
>>> len(encode_str_to_hexed_b64(data))
93336
```
